config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'change/locale/:locale' => 'locale#change_locale', as: :change_locale

  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: 'user/omniauth_callbacks'}

  scope "(:locale)", locale: /en|ru/ do
    get '/' => 'pages#home', as: :root_locale
    get 'users/edit' => 'user/settings#edit'
    devise_for :users,
                controllers: {
                  sessions: 'user/sessions',
                  passwords: 'user/passwords'
                },
                skip: :omniauth_callbacks
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resource :cart, only: [:show, :destroy], controller: :cart do
      post :add_item, on: :member
      post :update_item, on: :member
      post :update_coupon, on: :member
      delete 'remove/:id' => 'cart#remove_item', as: :remove_item
    end

    namespace :checkout do
      get 'start' => 'order#start', as: :start
      resource :addresses, only: [:edit, :update] do
        get '/' => 'addresses#edit', on: :member
      end
      resource :delivery, only: [:edit, :update], controller: :delivery do
        get '/' => 'delivery#edit', on: :member
      end
      resource :payment, only: [:edit, :update], controller: :payment do
        get '/' => 'payment#edit', on: :member
      end
      get 'confirm' => 'order#confirm', as: :confirm
      get 'complete' => 'order#to_queue', as: :to_queue
    end

    namespace :shop do
      resources :categories, only: :show
      resources :books, only: [:index, :show] do
        resources :reviews, only: [:new, :create]
      end
    end

    namespace :user do
      resources :orders, only: [:index, :show]
      resource :settings, only: [:edit] do
        member do
          post 'billing_address'
          post 'shipping_address'
          post 'email'
          post 'password'
          post 'remove_user'
          get 'billing_address' => 'settings#edit'
          get 'shipping_address' => 'settings#edit'
          get 'email' => 'settings#edit'
          get 'password' => 'settings#edit'
          get 'remove_user' => 'settings#edit'
        end
      end
    end
  end

  get 'forbidden', to: 'errors#render_403', as: :forbidden
  match '*a', to: 'errors#render_404', via: :all

end

app/controllers/shop/books_controller.rb
module Shop
  # :nodoc:
  class BooksController < ::ApplicationController
    def index
      @books = Book.page(params[:page]).per(6)
    end

    def show
      @book = Book.find(params[:id])
      @reviews = @book.approved_reviews
      @in_cart = @order.cart_item(@book.id)
      @cart = Cart.new(book_id: @book.id, book_count: 1)
    rescue
      redirect_to shop_books_path
    end
  end
end

app/controllers/shop/categories_controller.rb
module Shop
  # :nodoc:
  class CategoriesController < ::ApplicationController
    def show
      @category = Category.find(params[:id])
      @books = @category.books.page(params[:page]).per(6)
    rescue
      redirect_to shop_books_path
    end
  end
end

app/controllers/shop/reviews_controller.rb
module Shop
  # :nodoc:
  class ReviewsController < ::ApplicationController
    before_action :authenticate_user!
    authorize_resource

    def new
      @review = Review.new(book: Book.find(params[:book_id]))
    rescue
      redirect_to :back
    end

    def create
      book = Book.find(params[:book_id])
      @review = Review.new(review_params)
      @review.user = current_user
      @review.book = book
      return render :new unless @review.save
      redirect_to shop_book_path(params[:book_id]),
                  notice: t('views.shop.review_notice')
    rescue
      redirect_to :back
    end

    protected

    def review_params
      params.require(:review).permit(:title, :text, :vote)
    end
  end
end

app/views/shop/reviews/new.html.haml
.row
  .col-sm-4.text-center
    %h2= "#{t('views.review.new_review_title').mb_chars.capitalize}:"
  .col-sm-8
    %h3= link_to @review.book.title, shop_book_path(@review.book)
.row
  .col-sm-offset-2.col-sm-8
    = form_for @review, url: shop_book_reviews_path, html: {role: 'form'} do |review_f|
      = review_f.hidden_field :user_id, value: current_user.id
      = review_f.hidden_field :book_id, value: @review.book.id
      .form-group
        = review_f.label :title
        = review_f.text_field :title, class: 'form-control'
      .form-group
        = review_f.label :vote
        .vote
      .form-group
        = review_f.label :text
        = review_f.text_area :text, class: 'form-control', rows: '10'
      .form-group
        .pull-left= review_f.submit t('btn.add').mb_chars.capitalize, class: 'btn btn-primary'
        .pull-right= link_to t('btn.cancel').mb_chars.capitalize, shop_book_path(@review.book), class: 'btn btn-default'