config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'change/locale/:locale' => 'locale#change_locale', as: :change_locale

  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: 'user/omniauth_callbacks'}

  scope "(:locale)", locale: /en|ru/ do
    get '/' => 'pages#home', as: :root_locale
    get 'users/edit' => 'user/settings#edit'
    devise_for :users,
                controllers: {
                  sessions: 'user/sessions',
                  passwords: 'user/passwords'
                },
                skip: :omniauth_callbacks
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resource :cart, only: [:show, :destroy], controller: :cart do
      post :add_item, on: :member
      post :update_item, on: :member
      post :update_coupon, on: :member
      delete 'remove/:id' => 'cart#remove_item', as: :remove_item
    end

    namespace :checkout do
      get 'start' => 'order#start', as: :start
      resource :addresses, only: [:edit, :update] do
        get '/' => 'addresses#edit', on: :member
      end
      resource :delivery, only: [:edit, :update], controller: :delivery do
        get '/' => 'delivery#edit', on: :member
      end
      resource :payment, only: [:edit, :update], controller: :payment do
        get '/' => 'payment#edit', on: :member
      end
      get 'confirm' => 'order#confirm', as: :confirm
      get 'complete' => 'order#to_queue', as: :to_queue
    end

    namespace :shop do
      resources :categories, only: :show
      resources :books, only: [:index, :show] do
        resources :reviews, only: [:new, :create]
      end
    end

    namespace :user do
      resources :orders, only: [:index, :show]
      resource :settings, only: [:edit] do
        member do
          post 'billing_address'
          post 'shipping_address'
          post 'email'
          post 'password'
          post 'remove_user'
          get 'billing_address' => 'settings#edit'
          get 'shipping_address' => 'settings#edit'
          get 'email' => 'settings#edit'
          get 'password' => 'settings#edit'
          get 'remove_user' => 'settings#edit'
        end
      end
    end
  end

  get 'forbidden', to: 'errors#render_403', as: :forbidden
  match '*a', to: 'errors#render_404', via: :all

end

app/models/user.rb
# :nodoc:
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :lockable
  devise :omniauthable, omniauth_providers: [:facebook]

  has_many :orders
  has_many :reviews
  has_many :soc_auths
  has_one :shipping_address,  class_name: 'Address',
                              foreign_key: :shipping_for_user
  has_one :billing_address,   class_name: 'Address',
                              foreign_key: :billing_for_user

  rails_admin do
    object_label_method do
      :email
    end
    show do
      include_all_fields
      fields :billing_address, :shipping_address do
        pretty_value { bindings[:view].admin_pretty_address(value) if value }
      end
    end
  end

  def admin?
    ENV['ADMIN_EMAIL'] == email
  end

  def order_in_progress
    order = orders.in_progress
    order.try(:id) && order.order_state ? order : nil
  end

  def data
    return nil if soc_auths.empty?
    soc_auths.reverse.each_with_object({}) do |auth, res|
      if auth.try(:data) && auth.data.is_a?(Hash)
        res.merge!(auth.data.delete_if { |_key, val| val.blank? })
      end
      res
    end
  end
end

app/controllers/user/omniauth_callbacks_controller.rb
# :nodoc:
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @auth = SocAuth.where(uid: data[:uid], provider: data[:provider]).first
    unless @auth
      @user = User.find_or_create_by!(email: data[:info][:email]) do |user|
        user.password = Devise.friendly_token[0, 20]
      end
      @auth = SocAuth.create!(
        uid: data[:uid],
        provider: data[:provider],
        user_id: @user.id,
        data: {
          first_name: data[:info][:first_name],
          last_name: data[:info][:last_name]
        }
      )
    end
    sign_in_and_redirect @auth.user
  rescue StandardError => e
    logger.error 'Facebook auth error: ' + e.message
    redirect_to new_user_session_path(locale: session[:locale]),
                alert: t('oauth.msg.error')
  end

  protected

  def data
    request.env['omniauth.auth']
  end
end

app/controllers/user/orders_controller.rb
# :nodoc:
class User::OrdersController < ApplicationController
  before_action :authenticate_user!

  def index
    @orders_in_queue = Order.accessible_by(current_ability).in_queue
    @orders_in_delivery = Order.accessible_by(current_ability).in_delivery
    @orders_delivered = Order.accessible_by(current_ability).delivered
  end

  def show
    @viewing_order = Order.find(params[:id].to_i)
    authorize! :show, @viewing_order
  rescue
    redirect_to user_orders_path
  end
end

app/controllers/user/passwords_controller.rb
# :nodoc:
class User::PasswordsController < Devise::PasswordsController
  protected

  def after_resetting_password_path_for(_resource)
    root_locale_path
  end
end

app/controllers/user/sessions_controller.rb
# :nodoc:
class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    cart_items = session[OrderFactory::STORAGE_KEY]
    coupon_id = session[OrderFactory::COUPON_STORAGE_KEY]
    super
    session[OrderFactory::STORAGE_KEY] = cart_items
    session[OrderFactory::COUPON_STORAGE_KEY] = coupon_id
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/settings_controller.rb
# :nodoc:
class User::SettingsController < ApplicationController
  before_action :authenticate_user!

  def edit
    define_variables
  end

  def billing_address
    @billing_address = Address.new(address_params(:billing))
    if @billing_address.valid?
      if current_user.billing_address
        current_user.billing_address.update(address_params(:billing))
      else
        current_user.billing_address = @billing_address
      end
      redirect_to edit_user_settings_path
    else
      define_variables
      render :edit
    end
  end

  def shipping_address
    @shipping_address = Address.new(address_params(:shipping))
    if @shipping_address.valid?
      if current_user.shipping_address
        current_user.shipping_address.update(address_params(:shipping))
      else
        current_user.shipping_address = @shipping_address
      end
      redirect_to edit_user_settings_path
    else
      define_variables
      render :edit
    end
  end

  def email
    if current_user.update(user_params)
      redirect_to edit_user_settings_path
    else
      current_user.reload
      define_variables
      render :edit
    end
  end

  def password
    if current_user.update_with_password(user_params)
      sign_in current_user, bypass: true
      redirect_to edit_user_settings_path,
                  notice: t('views.user.settings.password.success_msg')
    else
      current_user.reload
      define_variables
      render :edit
    end
  end

  def remove_user
    if params[:confirm]
      current_user.soc_auths.each(&:destroy!)
      current_user.destroy!
      redirect_to new_user_session_path,
                  notice: t('views.user.settings.remove_account.success_msg')
    else
      label_confirm = t('views.user.settings.remove_account.confirm').mb_chars
                                                                     .capitalize
      redirect_to edit_user_settings_path,
                  alert: t('views.user.settings.remove_account.error_msg',
                           label: label_confirm)
    end
  rescue StandardError => e
    logger.error 'Remove user error: ' + e.message
    redirect_to edit_user_settings_path, alert: t('.error')
  end

  protected

  def address_params(type)
    params.require(:user).require(type).require(:address)
          .permit(:first_name, :last_name, :address_line,
                  :city, :country, :zip, :phone)
  end

  def user_params
    params.require(:user).permit(:email, :current_password,
                                 :password, :password_confirmation)
  end

  def define_variables
    @user ||= current_user
    @billing_address ||= current_user.billing_address ||
                         Address.new(current_user.data)
    @shipping_address ||= current_user.shipping_address ||
                          Address.new(current_user.data)
    @email ||= current_user.email
  end
end

app/views/user/settings/edit.html.haml
%h1 Settings
.row
  .col-sm-6
    = form_for @user, method: :post, url: billing_address_user_settings_path, html: {role: 'form', id: 'edit_user_billing_address'} do |user_f|
      = render "partials/address_fields", address: @billing_address, type: :billing, object: user_f
      .form-group
        = user_f.submit t('btn.save').mb_chars.capitalize, class: 'btn btn-primary'
  .col-sm-6
    = form_for @user, method: :post, url: shipping_address_user_settings_path, html: {role: 'form', id: 'edit_user_shipping_address'} do |user_f|
      = render "partials/address_fields", address: @shipping_address, type: :shipping, object: user_f
      .form-group
        = user_f.submit t('btn.save').mb_chars.capitalize, class: 'btn btn-primary'
.row
  .col-sm-6
    = form_for @user, method: :post, url: email_user_settings_path, html: {role: 'form', id: 'edit_user_email'} do |user_f|
      %h3.text-center= t('activerecord.attributes.user.email').mb_chars.upcase
      %br
      .form-group
        = user_f.text_field :email, class: 'form-control'
        - error_message @user, :email
      .form-group
        =user_f.submit t('btn.save').mb_chars.capitalize, class: 'btn btn-primary'
    %br
    %hr
    %h3= t('views.user.settings.remove_account.title').mb_chars.upcase
    = form_tag(remove_user_user_settings_path, id: 'remove_user_account') do
      .form-group
        = submit_tag t('views.user.settings.remove_account.btn').mb_chars.upcase, class: 'btn btn-danger'
      .form-group
        = check_box_tag :confirm
        = label_tag :confirm, t('views.user.settings.remove_account.confirm').mb_chars.capitalize

  .col-sm-6
    = form_for @user, method: :post, url: password_user_settings_path, html: {role: 'form', id: 'change_user_password'} do |user_f|
      %h3.text-center= t('activerecord.attributes.user.password').mb_chars.upcase
      .form-group
        = user_f.label :current_password, t('views.user.settings.password.old_lable').mb_chars.capitalize
        = user_f.password_field :current_password, class: 'form-control'
        - error_message @user, :current_password
      .form-group
        = user_f.label :password, t('views.user.settings.password.new_lable').mb_chars.capitalize
        = user_f.password_field :password, autocomplete: 'off', class: 'form-control'
        - error_message @user, :password
      .form-group
        = user_f.label :password_confirmation, t('views.user.settings.password.confirm_lable').mb_chars.capitalize
        = user_f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control'
        - error_message @user, :password_confirmation
      .form-group
        = user_f.submit t('btn.save').mb_chars.capitalize, class: 'btn btn-primary'