config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'change/locale/:locale' => 'locale#change_locale', as: :change_locale

  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: 'user/omniauth_callbacks'}

  scope "(:locale)", locale: /en|ru/ do
    get '/' => 'pages#home', as: :root_locale
    get 'users/edit' => 'user/settings#edit'
    devise_for :users,
                controllers: {
                  sessions: 'user/sessions',
                  passwords: 'user/passwords'
                },
                skip: :omniauth_callbacks
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resource :cart, only: [:show, :destroy], controller: :cart do
      post :add_item, on: :member
      post :update_item, on: :member
      post :update_coupon, on: :member
      delete 'remove/:id' => 'cart#remove_item', as: :remove_item
    end

    namespace :checkout do
      get 'start' => 'order#start', as: :start
      resource :addresses, only: [:edit, :update] do
        get '/' => 'addresses#edit', on: :member
      end
      resource :delivery, only: [:edit, :update], controller: :delivery do
        get '/' => 'delivery#edit', on: :member
      end
      resource :payment, only: [:edit, :update], controller: :payment do
        get '/' => 'payment#edit', on: :member
      end
      get 'confirm' => 'order#confirm', as: :confirm
      get 'complete' => 'order#to_queue', as: :to_queue
    end

    namespace :shop do
      resources :categories, only: :show
      resources :books, only: [:index, :show] do
        resources :reviews, only: [:new, :create]
      end
    end

    namespace :user do
      resources :orders, only: [:index, :show]
      resource :settings, only: [:edit] do
        member do
          post 'billing_address'
          post 'shipping_address'
          post 'email'
          post 'password'
          post 'remove_user'
          get 'billing_address' => 'settings#edit'
          get 'shipping_address' => 'settings#edit'
          get 'email' => 'settings#edit'
          get 'password' => 'settings#edit'
          get 'remove_user' => 'settings#edit'
        end
      end
    end
  end

  get 'forbidden', to: 'errors#render_403', as: :forbidden
  match '*a', to: 'errors#render_404', via: :all

end

app/views/partials/_address_fields.html.haml
-# type - type of address (for exemple :billing)
-# object - object of current form
-# address - address object
%h3.text-center= t("activerecord.attributes.user.#{type.to_s}_address").mb_chars.upcase
= object.fields_for type do |type_f|
  = type_f.fields_for address do |address_f|
    .form-group
      = address_f.label :first_name
      = address_f.text_field :first_name, class: 'form-control'
      - error_message address, :first_name
    .form-group
      = address_f.label :last_name
      = address_f.text_field :last_name, class: 'form-control'
      - error_message address, :last_name
    .form-group
      = address_f.label :address_line
      = address_f.text_field :address_line, class: 'form-control'
      - error_message address, :address_line
    .form-group
      = address_f.label :city
      = address_f.text_field :city, class: 'form-control'
      - error_message address, :city
    .form-group
      = address_f.label :country
      = address_f.text_field :country, class: 'form-control'
      - error_message address, :country
    .form-group
      = address_f.label :zip
      = address_f.text_field :zip, class: 'form-control'
      - error_message address, :zip
    .form-group
      = address_f.label :phone
      %span.small= "(#{t('.example')} +380961111111)"
      = address_f.text_field :phone, class: 'form-control'
      - error_message address, :phone

app/views/partials/_board_of_books.html.haml
- unless @books.empty?
  - books_buffer = []
  - count_in_row = 3
  - @books.each_with_index do |book, i|
    - books_buffer << book
    - next unless books_buffer.count == count_in_row || @books.count - 1 == i
    = render 'partials/row_of_books', books: books_buffer, count: count_in_row
    - books_buffer = []
  .text-center= paginate @books

app/views/partials/_cart_table.html.haml
- unless order.cart_items.empty?
  - editable ||= false
  - show_shipping_price ||= false
  - show_order_total ||= false
  %table.table
    %thead
      %tr
        %th.text-center{colspan: 2}= t('activerecord.models.book.one').mb_chars.upcase
        %th.text-center= t('activerecord.attributes.book.price').mb_chars.upcase
        %th.text-center= t('views.partials.cart_table.title.qty').mb_chars.upcase
        %th.text-center= t('views.partials.cart_table.title.total').mb_chars.upcase
        %th
    %tbody.cart_items
      - order.cart_items.each do |item|
        %tr.cart_item{'data-book_id': item.book_id}
          %td.cart_item_image= image_tag(item.book.image.thumb, class: 'img-thumbnail')
          %td.cart_item_text
            %h4= link_to item.book.title, shop_book_path(item.book)
            %p.description= item.book.short_description
          %td.cart_item_price.price= "$ %.02f" % item.book.price
          %td.cart_item_count.text-center
            - if editable
              = number_field_tag(:count, item.book_count, class: 'form-control', in: 1..20, step: 1)
            - else
              %p.lead= item.book_count
          %td.cart_item_total_price.price
            $
            %span= "%.02f" % item.total_price
          - if editable
            %td
              = link_to remove_item_cart_path(item.book.id), method: :delete, title: t('btn.remove') do
                == <i class='fa fa-remove fa-lg'></i>
    %tbody.cart_total
      %tr.price_row
        %td.text-right{colspan: 4}= "#{t('views.partials.cart_table.subtotal').mb_chars.upcase}:"
        %td.items_total.price
          $
          %span= "%.02f" % order.item_total
      - if order.item_discount > 0
        %tr.price_row
          %td.text-right{colspan: 4}
            = t('activerecord.attributes.coupon.discount').mb_chars.upcase
            = "(#{t('activerecord.models.coupon.one')}"
            == ##{order.coupon_by_strategy.code} : #{order.coupon_by_strategy.discount * 100}%):
          %td.items_discount.price
            == -$
            %span= "%.02f" % order.item_discount
        %tr.price_row
          %td.text-right{colspan: 4}= "#{t('views.partials.cart_table.subtotal_with_discount').mb_chars.upcase}:"
          %td.items_total_with_discount.price
            $
            %span= "%.02f" % order.item_total_with_discount
      - if show_shipping_price
        %tr.price_row
          %td.text-right{colspan: 4}= "#{t('views.partials.cart_table.shipping').mb_chars.upcase}:"
          %td.shipping_price.price
            $
            %span= "%.02f" % (order.delivery.try(:price) || 0)
      - if show_order_total
        %tr.price_row
          %td.text-right{colspan: 4}= "#{t('views.partials.cart_table.order_total').mb_chars.upcase}:"
          %td.order_total.price
            $
            %span= "%.02f" % order.order_total
- else
  %h3.text-center
    = t('views.partials.cart_table.cart_empty').mb_chars.capitalize
    = link_to t('btn.go_to_shop').mb_chars.capitalize, shop_books_path, class: 'btn btn-primary'

app/views/partials/_category_navigation.html.haml
%h4= t('views.partials.shop_by_categories.title')
= render_navigation &category_menu_proc('list-group category_menu', 'list-group-item')

app/views/partials/_messages.html.haml
.container
  -if notice
    .alert.alert-success
      = notice
      %button.close{type: 'button', 'data-dismiss': 'alert', 'aria-hidden': 'true'}
        &times;

  -if alert
    .alert.alert-danger
      = alert
      %button.close{type: 'button', 'data-dismiss': 'alert', 'aria-hidden': 'true'}
        &times;

app/views/partials/_review.html.haml
.review
  .review_head
    %span.vote_ready{'data-score': review.vote}
    %span= review.title
    %span.small= l(review.created_at, format: :review)
  .review_author
    = t('views.partials.review.by')
    %span.author_name= review.user.email
  .review_text= review.text

app/views/partials/_row_of_books.html.haml
.row.row_of_books
  - books.each do |book|
    %div{class: "col-sm-#{12/count} "}
      .div_image.text-center
        = image_tag(book.image.thumb, class: 'img-thumbnail')
      %h4.text-center= link_to book.title, shop_book_path(book)
      .price.text-center
        %strong
          = "$#{book.price}"