config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'change/locale/:locale' => 'locale#change_locale', as: :change_locale

  devise_for :users, only: :omniauth_callbacks,
              controllers: {omniauth_callbacks: 'user/omniauth_callbacks'}

  scope "(:locale)", locale: /en|ru/ do
    get '/' => 'pages#home', as: :root_locale
    get 'users/edit' => 'user/settings#edit'
    devise_for :users,
                controllers: {
                  sessions: 'user/sessions',
                  passwords: 'user/passwords'
                },
                skip: :omniauth_callbacks
    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    resource :cart, only: [:show, :destroy], controller: :cart do
      post :add_item, on: :member
      post :update_item, on: :member
      post :update_coupon, on: :member
      delete 'remove/:id' => 'cart#remove_item', as: :remove_item
    end

    namespace :checkout do
      get 'start' => 'order#start', as: :start
      resource :addresses, only: [:edit, :update] do
        get '/' => 'addresses#edit', on: :member
      end
      resource :delivery, only: [:edit, :update], controller: :delivery do
        get '/' => 'delivery#edit', on: :member
      end
      resource :payment, only: [:edit, :update], controller: :payment do
        get '/' => 'payment#edit', on: :member
      end
      get 'confirm' => 'order#confirm', as: :confirm
      get 'complete' => 'order#to_queue', as: :to_queue
    end

    namespace :shop do
      resources :categories, only: :show
      resources :books, only: [:index, :show] do
        resources :reviews, only: [:new, :create]
      end
    end

    namespace :user do
      resources :orders, only: [:index, :show]
      resource :settings, only: [:edit] do
        member do
          post 'billing_address'
          post 'shipping_address'
          post 'email'
          post 'password'
          post 'remove_user'
          get 'billing_address' => 'settings#edit'
          get 'shipping_address' => 'settings#edit'
          get 'email' => 'settings#edit'
          get 'password' => 'settings#edit'
          get 'remove_user' => 'settings#edit'
        end
      end
    end
  end

  get 'forbidden', to: 'errors#render_403', as: :forbidden
  match '*a', to: 'errors#render_404', via: :all

end

app/controllers/checkout/addresses_controller.rb
module Checkout
  # :nodoc:
  class AddressesController < BaseController
    def edit
      @step = 1
      order.billing_address  ||= current_user.try(:billing_address)  ||
                                 Address.new(current_user.try(:data))
      order.shipping_address ||= current_user.try(:shipping_address) ||
                                 Address.new(current_user.try(:data))
    end

    def update
      @step = 1
      order.create_or_update_billing_address(address_params(:billing))
      if params[:once_address]
        order.shipping_address = order.billing_address
      else
        order.create_or_update_shipping_address(address_params(:shipping))
      end
      order.save!
      if order.billing_address.errors.any? || order.shipping_address.errors.any?
        render :edit
      else
        redirect_to edit_checkout_delivery_path
      end
    end

    protected

    def address_params(type)
      params.require(:order).require(type).require(:address)
            .permit(:first_name, :last_name, :address_line, :city,
                    :country, :zip, :phone)
    end
  end
end

app/controllers/checkout/base_controller.rb
module Checkout
  # :nodoc:
  class BaseController < ::ApplicationController
    before_filter :check_order, except: :start

    def check_step!(step)
      check_configs.each do |conf|
        return if step == conf[:step]
        return redirect_to conf[:path] unless conf[:condition]
      end
    end

    protected

    def check_order
      redirect_to cart_path unless @order.persisted?
    end

    def check_configs
      [
        {
          step: 1,
          path: edit_checkout_addresses_path,
          condition: @order.billing_address
        },
        {
          step: 2,
          path: edit_checkout_delivery_path,
          condition: @order.delivery
        },
        {
          step: 3,
          path: edit_checkout_payment_path,
          condition: @order.credit_card
        },
        {
          step: 4,
          path: checkout_confirm_path,
          condition: @order.order_state == OrderState.in_queue
        }
      ]
    end
  end
end

app/controllers/checkout/delivery_controller.rb
module Checkout
  # :nodoc:
  class DeliveryController < BaseController
    def edit
      @step = 2
      check_step! @step
      @deliveries = Delivery.all
    end

    def update
      @step = 2
      check_step! @step
      @order.delivery = Delivery.find(delivery_params[:delivery])
      @order.save!
      redirect_to edit_checkout_payment_path
    rescue
      redirect_to :back
    end

    protected

    def delivery_params
      params.require(:order).permit(:delivery)
    end
  end
end

app/controllers/checkout/order_controller.rb
module Checkout
  # :nodoc:
  class OrderController < BaseController
    def start
      unless @order.persisted?
        @order.order_state = OrderState.in_progress
        return redirect_to :back unless @order.save_with_cart_items
      end
      redirect_to edit_checkout_addresses_path
    end

    def confirm
      @step = 4
      check_step! @step
    end

    def to_queue
      @step = 4
      check_step! @step
      @order.order_state = OrderState.in_queue
      @order.save!
      @curent_order = @order
      @order = Order.new
      render 'show'
    end
  end
end

app/controllers/checkout/payment_controller.rb
module Checkout
  # :nodoc:
  class PaymentController < BaseController
    def edit
      @step = 3
      check_step! @step
      @order.credit_card ||= CreditCard.new
    end

    def update
      @step = 3
      @order.create_or_update_credit_card(credit_card_params)
      if @order.credit_card.errors.any?
        render :edit
      else
        @order.save!
        redirect_to checkout_confirm_path
      end
    end

    protected

    def credit_card_params
      params.require(:credit_card).permit(:number, :code, :expiration_date)
    end
  end
end

app/helpers/checkout/order_helper.rb
module Checkout
  # :nodoc:
  module OrderHelper
    def pretty_address(address)
      haml_tag :span, "#{address.first_name} #{address.last_name}"
      haml_tag :br
      haml_tag :span, "#{address.address_line}"
      haml_tag :br
      haml_tag :span, "#{address.city} #{address.zip}"
      haml_tag :br
      haml_tag :span, "#{address.country}"
      haml_tag :br
      haml_tag :span, "Phone #{address.phone}"
    end

    def pretty_credit_card(card)
      haml_tag :span, "**** **** **** #{card.number[-4, 4]}"
      haml_tag :br
      haml_tag :span, card.expiration_date.strftime('%m/%Y')
    end
  end
end

app/views/checkout/payment/edit.html.haml
- content_for :checkout_data do
  = form_for @order, url: checkout_payment_path, method: 'put', html: {role: 'form'} do |order|
    .row
      .col-sm-6
        %h3.text-center= t('views.checkout.panel.payment').mb_chars.upcase
        = fields_for @order.credit_card do |credit_card_f|
          .form-group
            = credit_card_f.label :number, t('activerecord.attributes.credit_card.number').mb_chars.capitalize
            %span.small= "(#{t('.example')} 4539795011193619)"
            = credit_card_f.text_field :number, class: 'form-control'
            - error_message @order.credit_card, :number
          .form-group
            = credit_card_f.label :expiration_date, t('activerecord.attributes.credit_card.expiration_date').mb_chars.capitalize
            .expiration_date
              = credit_card_f.date_select :expiration_date, {discard_day: true,
                                                          use_month_numbers: true,
                                                          start_year: Date.today.year,
                                                          end_year: Date.today.year + 10},
                                                          {class: 'form-control'}
            - error_message @order.credit_card, :expiration_date
          .form-group
            = credit_card_f.label :code, t('activerecord.attributes.credit_card.code').mb_chars.capitalize
            = credit_card_f.text_field :code, class: 'form-control', size: 3, maxlength: 3
            - error_message @order.credit_card, :code
        .form-group
          = order.submit t('views.checkout.btn.save_and_cont').mb_chars.capitalize, class: 'btn btn-primary form-control'

= render 'checkout/wraper', step: @step